[package]
name = "hello"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = "0.4.1"
log = "0.4.14"
serde = "1.0.133"
simple_logger = "1.16.0"
tokio = "1.14.0"
